# Generated by Django 6.0.4 on 2026-04-11 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField()),
                ('body_content', models.TextField(help_text="HTML content. Use <span class='highlight-link' data-content-id='ID'>text</span> to add interactive highlights.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.subcategory')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('subcategory', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='InteractiveContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text / Rich HTML'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video (Upload)'), ('youtube', 'YouTube Video')], max_length=20)),
                ('text_content', models.TextField(blank=True, help_text="For 'text' type — can include HTML with bold/italic/underline")),
                ('image', models.ImageField(blank=True, null=True, upload_to='interactive/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='interactive/audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='interactive/videos/')),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL e.g. https://www.youtube.com/watch?v=...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_contents', to='content.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AccordionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content for this accordion section')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_open_by_default', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_sections', to='content.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
