# Generated by Django 6.0.4 on 2026-04-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_image_to_paymentinstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
