# Generated by Django 6.0.4 on 2026-04-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_subcategory_teacher_coursechangerequest_coursequiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechangerequest',
            name='requested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_add_requests', to='content.category'),
        ),
        migrations.AddField(
            model_name='coursechangerequest',
            name='requested_course_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coursechangerequest',
            name='requested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursechangerequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='content.subcategory'),
        ),
    ]
