# Generated by Django 6.0.4 on 2026-04-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_module_coursequiz_module_coursevideo_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quizzes', to='content.subject'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='content.subject'),
        ),
    ]
