# Generated by Django 6.0.4 on 2026-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_coursequiz_subject_alter_coursevideo_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
