# Generated by Django 6.0.4 on 2026-04-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_module_editor_and_accordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text / Rich HTML'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video (Upload)'), ('youtube', 'YouTube Video')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to='content.module'),
        ),
    ]
